version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - pip install mkdocs-material mkdocstrings[python]
    - cat mkdocs.yml
    - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

mkdocs:
  configuration: mkdocs.yml
